basePath: /
definitions:
  handler.CallbackResponse:
    properties:
      code:
        example: 0
        type: integer
      message:
        example: success
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@xiangshoufu.com
    name: API Support
  description: 代理商分润管理系统 - 支付通道回调处理服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 8通道回调服务 API
  version: "1.0"
paths:
  /callback/{channel_code}:
    post:
      consumes:
      - application/json
      description: 接收各支付通道的回调通知，支持8个通道：HENGXINTONG(恒信通)、LAKALA(拉卡拉)、YEAHKA(乐刷)、SUIXINGFU(随行付)、LIANLIAN(连连)、SANDPAY(杉德)、FUIOU(富友)、HEEPAY(汇付天下)
      parameters:
      - description: 通道编码
        enum:
        - HENGXINTONG
        - LAKALA
        - YEAHKA
        - SUIXINGFU
        - LIANLIAN
        - SANDPAY
        - FUIOU
        - HEEPAY
        in: path
        name: channel_code
        required: true
        type: string
      - description: 回调数据（各通道格式不同）
        in: body
        name: body
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/handler.CallbackResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.CallbackResponse'
      summary: 支付通道回调
      tags:
      - 回调
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
